In [11]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd
import os.path
import sys
import pickle

In [12]:
corpus = ['El niño corre velozmente por el camino a gran velocidad .',
          'El coche rojo del niño es grande .',
          'El coche tiene un color rojo brillante y tiene llantas nuevas .',
          '¿ Las nuevas canicas del niño son color rojo ?'
]


In [13]:
#Representación vectorial por frecuencia
# ~ vectorizador_frecuencia = CountVectorizer()
vectorizador_frecuencia = CountVectorizer(token_pattern= r'(?u)\w+|\w+\n|\.|\¿|\?')
X = vectorizador_frecuencia.fit_transform(corpus)
print (vectorizador_frecuencia.get_feature_names_out())
#print (X)#sparse matrix
# ~ print (type(X))#sparse matrix
# ~ print (type(X.toarray()))#dense ndarray

#print('Representación vectorial por frecuencia')
print (X.toarray())


['.' '?' 'a' 'brillante' 'camino' 'canicas' 'coche' 'color' 'corre' 'del'
 'el' 'es' 'gran' 'grande' 'las' 'llantas' 'niño' 'nuevas' 'por' 'rojo'
 'son' 'tiene' 'un' 'velocidad' 'velozmente' 'y' '¿']
[[1 0 1 0 1 0 0 0 1 0 2 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0]
 [1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 2 1 0 0 1 0]
 [0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 1]]


In [14]:
#Use of Pickle
if (os.path.exists('X_vectorizador_tfidf.pkl')):
	print ('Ya existe')
	vector_file = open ('X_vectorizador_tfidf.pkl','rb')
	X = pickle.load(vector_file)
else:
	vector_file = open ('X_vectorizador_frecuencia.pkl','wb')
	vectorizador_frecuencia = CountVectorizer(token_pattern= r'(?u)\w+|\w+\n|\.|\¿|\?')
	X = vectorizador_frecuencia.fit_transform(corpus)
	pickle.dump(X, vector_file)
	vector_file.close()

print ('Representación vectorial frecuencia')
print (X.toarray())


Representación vectorial frecuencia
[[1 0 1 0 1 0 0 0 1 0 2 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0]
 [1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 2 1 0 0 1 0]
 [0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 1]]


In [15]:
#Use of Pickle
if (os.path.exists('X_vectorizador_frecuencia.pkl')):
	print ('Ya existe')
	vector_file = open ('X_vectorizador_frecuencia.pkl','rb')
	X = pickle.load(vector_file)
	#print('Representación vectorial por frecuencia')
	print (X.toarray())
else:
    print("PKL no existe")

Ya existe
[[1 0 1 0 1 0 0 0 1 0 2 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0]
 [1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 2 1 0 0 1 0]
 [0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 1]]


In [16]:
prueba1 = ['El coche rojo corre velozmente por el camino del niño es grande .']
prueba2 = [' No hay nada que ver con los documentos anteriores xd']

In [17]:

Y = vectorizador_frecuencia.transform(prueba1)
#print (vectorizador_frecuencia.get_feature_names_out())
#print (X)#sparse matrix
# ~ print (type(X))#sparse matrix
# ~ print (type(X.toarray()))#dense ndarray

print('\nRepresentación vectorial por frecuencia para X')
print (X.toarray())

print('\nRepresentación vectorial por frecuencia para Y con vocabulario de X')
print (Y.toarray())


Representación vectorial por frecuencia para X
[[1 0 1 0 1 0 0 0 1 0 2 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0]
 [1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 2 1 0 0 1 0]
 [0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 1]]

Representación vectorial por frecuencia para Y con vocabulario de X
[[1 0 0 0 1 0 1 0 1 1 2 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0]]


In [18]:
import math 

def cosine(x, y):
    val = sum(x[index] * y[index] for index in range(len(x)))
    sr_x = math.sqrt(sum(x_val**2 for x_val in x))
    sr_y = math.sqrt(sum(y_val**2 for y_val in y))
    res = val / (sr_x * sr_y)

    # Verificar si alguno de los vectores tiene magnitud 0
    if sr_x == 0 or sr_y == 0:
        return 0  # Similaridad de coseno es 0 si alguno es un vector nulo

    # Calcular y retornar el coseno
    res = val / (sr_x * sr_y)

    return res
	

In [19]:
# Convertir X y Y a arrays densos para pasar a la función de coseno
X_denso = X.toarray()
Y_denso = Y.toarray()

# Calcular el coseno entre el primer documento de X y Y

# Iterar a través de todos los documentos en X
for i in range(len(X_denso)):
    resultado_coseno = cosine(X_denso[i], Y_denso[0])
    print(f'Coseno entre X[{i}] y Y[0]: {resultado_coseno}')

Coseno entre X[0] y Y[0]: 0.7161148740394329
Coseno entre X[1] y Y[0]: 0.821583836257749
Coseno entre X[2] y Y[0]: 0.3450327796711771
Coseno entre X[3] y Y[0]: 0.24494897427831777


In [ ]:
path='/Users/sebastianloeza/Desktop/Escuela/6to/NLP/Practicas/Practica3/Similitud_archivos/Corpus1/Content-bigram-binary.pkl'
prueba_df = pd.read_csv('/Users/sebastianloeza/Desktop/Escuela/6to/NLP/Practicas/Practica3/Similitud_archivos/pruebacsv_normalized.csv')

col_map = {'Title': 'Title', 'Content': 'Content', 'Title + Content': 'Title_Content'}
rep_map = {
    'Unigram - Frecuencia': 'unigram_frequency', 'Unigram - Binario': 'unigram_binary', 'Unigram - TF-IDF': 'unigram_tfidf',
    'Bigram - Frecuencia': 'bigram_frequency', 'Bigram - Binario': 'bigram_binary', 'Bigram - TF-IDF': 'bigram_tfidf', 'Todas': None
}

if (os.path.exists(path)):
    print ('Ya existe')
    vector_file = open (path,'rb')
    X = pickle.load(vector_file)
else:
    print ('No existe')

prueba_df['Title_Content'] = prueba_df['Title'] + " " + prueba_df['Content']
Y = X.transform(prueba_df[col_map[col_choice]])
print(X)
print(pd.DataFrame(Y.toarray(), columns=X.get_feature_names_out()))
    
    